### ISSUE TITLE
function multiviewBiSC

### ISSUE THREAD

**Issue by qinghua-tao** [uta-smile/AAAI2015_Yeqing#1]
Hi, thanks for creating this repository, with which I'm comparing now.

However, I found there is no implementation for the main function  multiviewBiSC running the clustering for the proposed method in your AAAI2015 paper. 

Could you please update it?

Thanks in advance.

Best,

**Comment by hehuanma** [comment]
Thank you for your interests in our lab's work! Please check the updated MVSCCode folder.

**Comment by hehuanma** [comment]
FYI, please check the MVSCCode/func/MVSC.m, which should be identical to the multiviewBiSC function.

**Comment by qinghua-tao** [comment]
Thank you for the updates. The codes now are okay for reproduction.

Best,
